### ISSUE TITLE
友だち一覧画面のvisibilityについて

### ISSUE THREAD

**Issue by t4t5u0** [FLAT-ICT/FLAT-Android#6]
未承認の友だち、友だち一覧 をそれぞれbindingできれば、データがないときに表示を消すことって可能？ 現状だと多分どちらも消すしかできないよね？

**Comment by Sorasky4** [comment]
承認、拒否、(削除)の更新をgetFriends叩いて行うのなら、適切になるようになってるはずなんだけど、どちらも消すしかできないっていうのはどういう状況？

**Comment by t4t5u0** [comment]
"未承認の友だち" っていうRVは、0件のときに見えてる必要はあんまりないのかなぁって思っただけ

**Comment by Sorasky4** [comment]
ユーザーアクション時にgetでの更新を行わない(今回のモックのような場合)だと、そこに存在していることが保証できれば消せる感じかな。
アイテムの情報を親フラグメントは持っていなくて、全部RVのViewHolderが保持しているから、visibility弄るんじゃなくてポジション指定してRVから削除しなきゃいけない。

**Comment by Sorasky4** [comment]
あ、バグ修正のついでに何も考えずにこっちもやっちゃった

**Comment by t4t5u0** [comment]
```
git switch develop
git switch -C feature/**
git cherry-pick **
```

**Comment by Sorasky4** [comment]
ごめん、コミット1つだから今回それで対応できない
