### ISSUE TITLE
名前を変更を押すと名前がhogeになり、変更できない

### ISSUE THREAD

**Issue by atomic928** [FLAT-ICT/FLAT-Android#82]
**確認したバグ**
- 名前を変更を押すと名前がhogeになり、変更できない

**望ましい挙動**
- 名前を変更を押して、決定を押したら変更できるようにする。
- 決定を押したらその名前になるようにする

**Comment by funera1** [comment]
mock serverのデフォルト値が原因だったので、問題なし
